### ISSUE TITLE
如何修改 hexo-theme-matery 模板 | 上善若水

### ISSUE THREAD

**Issue by xinetzone** [xinetzone/hexo-matery#11]
https://xinetzone.github.io/zh-CN/3567ebbb.html 

 修改 /docs/ 目录下的 _config.yml下面介绍如何修改模板主题：https://github.com/blinkfox/hexo-theme-matery.git。
首先，在个人 github 创建一个 repo，比如：xin

**Comment by chris2000520** [comment]
厉害了

**Comment by Liang-zero** [comment]
这个留言怎么弄

**Comment by xinetzone** [comment]
运行：`hexo new page contact`，然后在主题目录下面的 `_config.yml` 中添加配置菜单导航的名称、路径和图标icon：

```yml
Contact:
    url: /contact
    icon: fas fa-comments
```
